# Topics
## 1. Quick Reminder: Objects in Python
## 2. Matrix Multiplication 
## 3 Matrix Manipulation in Python
## 4. Relaxation Method


In [1]:
import numpy as np
import matplotlib.pyplot as plt

## A reminder: everything in Python is an Object...for example:

In [3]:
''' 
a = 2 in python has a very different meaning
from int a = 2 in c.
'''
a = 2
b = int(-3)
print(a, b)
# __...__ : double underscore, or "dunder"
print(dir(a))

2 -3
['__abs__', '__add__', '__and__', '__bool__', '__ceil__', '__class__', '__delattr__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floor__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getnewargs__', '__gt__', '__hash__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__le__', '__lshift__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rrshift__', '__rshift__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__trunc__', '__xor__', 'bit_length', 'conjugate', 'denominator', 'from_bytes', 'imag', 'numerator', 'real', 'to_bytes']


In [4]:
print(a.__abs__(), b.__abs__())

2 3


In [5]:
# The default value at instantiation is 0
c = int()
print(c)

0


In [6]:
# Is it legal? If so, what does this mean? If not, why not? 
gint = int

In [7]:
d = gint(4)
print(d, type(d))

4 <class 'int'>


In [8]:
class hint(int):
    pass

e = hint(5)
print(e, type(e))
print(isinstance(e, hint), isinstance(e, int))

5 <class '__main__.hint'>
True True


In [9]:
# Is this ok?
print((-5).__abs__())

5


## 1. Matrix Multiplication and Dot Product

$M_1 = \begin{bmatrix}
 1 & 1.5 & 3 \\
 -1 & 11 & -1  \\
 0 & -1 & 10 \\
\end{bmatrix}$

$M_2 = \begin{bmatrix}
 10 & 1 & 2 \\
 1 & 1 & 4.3  \\
 2 & -1 & 10 \\
\end{bmatrix}$


$a = \begin{bmatrix} 1 & 2 & 3 \end{bmatrix}$

$b = \begin{bmatrix} 1 & 1/2 & 1/3 \end{bmatrix}$

$c = \begin{bmatrix} 2 & 2.5 & 1 \end{bmatrix}$

## Find -- by hand!: 

- ### $M_1 + M_2$
- ### $M_1^{T}$
- ### $M_1 M_2$
- ### $M_2 M_1$
- ### $M_1 a$
- ### $a \cdot b$
- ### $b \cdot c$

## 2. Matrix Manipulation in Python

In [10]:
'''Important:

For most purposes, 

M = np.matrix([[1., 1.5, 3.],
              [-1., 11., -1.],
              [0., -1., 10.]])

and

M = np.array([[1., 1.5, 3.],
              [-1., 11., -1.],
              [0., -1., 10.]])

give you the same thing.  But certain matrix methods don't apply to a numpy array 
(such as the inverse; note: .I and .getI() both give you the inverse.).

For the whole list of methods:

http://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html

or do 

>>> dir(M)

'''

import numpy as np
M1 = np.matrix([[1., 1.5, 3.],
              [-1., 11., -1.],
              [0., -1., 10.]])

M2 = np.matrix([[10., 1., 2.],
              [1., 1., 4.3],
              [2., -1., 10.]])

a = np.array([1., 2., 3.])
b = np.array([1., 1/2., 1/3.])

M_sum = M1 + M2
print('M_sum:')
print(M_sum)

# np.dot
# for 1D -- dot product
dot_product = np.dot(a, b)
print('dot_product:', dot_product)



M_sum:
[[ 11.    2.5   5. ]
 [  0.   12.    3.3]
 [  2.   -2.   20. ]]
dot_product: 3.0


In [11]:
'''
Note: (see below) some methods can be invoked as though they are 
attributes -- I'll explain later 
'''
print(dir(M1))
print()


['A', 'A1', 'H', 'I', 'T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__

In [12]:
'''A very useful attribute'''
print(M1.shape)
print(a.shape)

(3, 3)
(3,)


In [13]:
'''
Matrix manipulation in Python

Compare with the results obtained by hand above

'''
M1M2 = np.dot(M1, M2)
print('M_1M_2:')
print(M1M2)

M2M1 = np.dot(M2, M1)
print('M_2M_1:')
print(M2M1)



# another example of matrix multiplication
M1_op_a = np.dot(M1, a)
print('M1_op_a:')
print(M1_op_a)

# transpose
M1_T = M1.T
print('Transposed M1:')
print(M1_T)

# trace
print('M1_trace', M1.trace())

# inverse
print('M1_inverse:') 
print(M1.I)
print('...to verify (M1*M1_inverse):')
# Note: for most python operations, the numerical error is on the level of 1e-16.
print(np.dot(M1.I, M1))

M_1M_2:
[[ 17.5   -0.5   38.45]
 [ -1.    11.    35.3 ]
 [ 19.   -11.    95.7 ]]
M_2M_1:
[[   9.    24.    49. ]
 [   0.     8.2   45. ]
 [   3.   -18.   107. ]]
M1_op_a:
[[ 13.  18.  28.]]
Transposed M1:
[[  1.   -1.    0. ]
 [  1.5  11.   -1. ]
 [  3.   -1.   10. ]]
M1_trace [[ 22.]]
M1_inverse:
[[ 0.85826772 -0.14173228 -0.27165354]
 [ 0.07874016  0.07874016 -0.01574803]
 [ 0.00787402  0.00787402  0.0984252 ]]
...to verify (M1*M1_inverse):
[[  1.00000000e+00   0.00000000e+00   4.44089210e-16]
 [  0.00000000e+00   1.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00]]


In [14]:
'''
Singular matrices 
(not every singular matrix is as obvious as the one below)
'''
M3 = np.matrix([[0, 0, 0],
              [0, 0, 0],
              [0, 0, 0]])

print('M3_inverse:') 
print(M3.I)


M3_inverse:


LinAlgError: Singular matrix

In [17]:
'''How about this one: Singular or not?'''

M4 = np.matrix([[0, 0, 0],
              [3, 1, 1],
              [2, 2, -1]])


print('M4_inverse:') 
print(M4.I)

M4_inverse:


LinAlgError: Singular matrix

In [18]:
'''How about this one: Singular or not?'''

M5 = np.matrix([[0, 1, 2],
              [3, 0, 1],
              [2, 2, 0]])


print('M5_inverse:') 
print(M5.I)


M5_inverse:
[[-0.14285714  0.28571429  0.07142857]
 [ 0.14285714 -0.28571429  0.42857143]
 [ 0.42857143  0.14285714 -0.21428571]]


In [19]:
# To get the determinant
import numpy.linalg as LA
import numpy as np
M1 = np.matrix([[1., 1.5, 3.],
              [-1., 11., -1.],
              [0., -1., 10.]])
print("Determinant of M1", LA.det(M1))

Determinant of M1 127.0


## Quick Breakout

### Write a function that solves the following matrix equations.  You should catch the expected exception of a non-invertible matrix.

### Mx = b

### A) 
`M1 = np.matrix([[1., 1.5, 3.],[-1., 11., -1.],[0., -1., 10.]]) and b = np.array([1., 1/2., 1/3.])`

### B) 
`M2 = np.matrix([[1.,0., 0.],[-2., 0., 0.],[4., 6., 1.]]) and c = np.array([1., 2., 3.])`

### C) 
`M3 = np.matrix([[-3. , -5., 1.], [9. ,14., 1.],  [18., 29., -2.]]) and d = np.array([3., 2., 1.])`

In [28]:
def solve_eqn(M, b):
    try:
        Minv = M.I
    except:
        print('Singular Matrix: No inverse.')
    else:
        return np.dot(Minv, b)

M1 = np.matrix([[1., 1.5, 3.],[-1., 11., -1.],[0., -1., 10.]])
b = np.array([1., 1/2., 1/3.])

print(solve_eqn(M1, b))

[[ 0.69685039  0.11286089  0.04461942]]


In [29]:
M1 = np.matrix([[1., 1.5, 3.],[-1., 10., -1.],[0., -1., 10.]]) 
b = np.array([1., 1/2., 1/3.])
soln = solve_eqn(M1, b)
print('Solution:', soln)

Solution: [[ 0.67948718  0.12250712  0.04558405]]


In [30]:
M2 = np.matrix([[1.,0., 0.],[-2., 0., 0.],[4., 6., 1.]]) 
c = np.array([1., 2., 3.])
soln = solve_eqn(M2, c)
print('Solution:', soln)

Singular Matrix: No inverse.
Solution: None


In [31]:
M3 = np.matrix([[-3. , -5., 1.], [9. ,14., 1.],  [18., 29., -2.]])
d = np.array([3., 2., 1.])
soln = solve_eqn(M3, d)
print('Solution:', soln)
# print(M2.I)
# print(LA.det(M2))

Solution: [[  1.69023986e+16  -1.06751991e+16  -2.66879978e+15]]


## End of week 6-1