# Topics

## 1. Representation Errors
## 2. Arrays and Numpy
## 3. Matplotlib

In [3]:
import math

# New import.  Typically:
import numpy as np


- Can save code in notebook as .py: File --> Download as-->Python(.py)

- How to write raw text (instead of code) in cells.

## Representation Error

- ### 1/3 does NOT have an exact representation in the digital system using a finite number of digits

- ### 0.1 does NOT have an exact representation in the digital system using a finite number of bits

In [1]:
# check this out:
0.10000000000000001 == 0.10

True

In [2]:
format(0.1, '.10f')

'0.1000000000'

In [3]:
format(0.1, '.16f')

'0.1000000000000000'

In [4]:
# below you will see why you get about 16 significant figures that are accurate, 
# but not beyond.
format(0.1, '.17f')

'0.10000000000000001'

## These days, usually one doesn't have to worry about it.  

### For more:

https://docs.python.org/3/tutorial/floatingpoint.html#representation-error

"Almost all machines today (November 2000) use IEEE-754 floating point arithmetic, and almost all platforms map Python floats to IEEE-754 “double precision”. 754 doubles contain 53 bits of precision"

### 2^53 ~ 1e16 --> this roughly translates to 16 significant figures of accurarcy

## Numpy Arrays

An array object can be viewed as a variant of a list, but with the following assumptions and features: 

• All elements must be of the same type, usually integers, real or complex numbers, or strings, for efficient numerical computing and storage. 

• The number of elements must be known when the array is created. 

• Arrays are not part of standard Python - one needs an additional package called Numerical Python, often abbreviated as NumPy. The Python name of the package, to be used in import statements, is numpy. 

• With numpy, a wide range of mathematical operations can be done on the entire array, thereby removing the need for loops over array elements. This is commonly called vectorization and may cause a dramatic speed-up of Python programs (and greatly enhance the readability of your code). 

• Arrays with one index are often called vectors. Arrays with two indices are used as an efficient data structure for tables, instead of lists of lists. Arrays can also have three or more indices.


In [5]:
(0.1 + 0.1 + 0.1) == 0.3

False

In [8]:
# same representation error for numpy
arr2 = np.array([0.1, 0.1, 0.1, 0.3])
sum0to2 = arr2[0] + arr2[1] + arr2[2] 
elem3 = arr2[3]

print(sum0to2)
print(elem3)
print(sum0to2 == elem3)

0.3
0.3
False


## Numpy vs. List Comprehension.  Numpy is

- ### Faster
- ### Syntactically more intuitive

In [9]:
# turning a list into a numpy array
r = range(1, 100)
a = np.array(r)   # a is an array; or in the CS lingo: a vector.
print(type(r), type(a))
print(a)

<class 'range'> <class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50
 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75
 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [4]:
%timeit [math.sin(x) for x in r]

NameError: name 'r' is not defined

In [11]:
%timeit np.sin(a)

2.09 µs ± 52.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Useful Numpy Functions

In [5]:
b = np.zeros(10)  
print(b, type(b))

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.] <class 'numpy.ndarray'>


In [6]:
c = np.ones(10)  
print(c, type(c))

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.] <class 'numpy.ndarray'>


In [7]:
# note: linspace is inclusive at BOTH ends
d = np.linspace(1, 12.4, 20)
print(d, type(d))
print(len(d))

[  1.    1.6   2.2   2.8   3.4   4.    4.6   5.2   5.8   6.4   7.    7.6
   8.2   8.8   9.4  10.   10.6  11.2  11.8  12.4] <class 'numpy.ndarray'>
20


In [8]:
# accessing an individual element of an array
a = np.zeros(10)
print(a[3])
a[2] = 1
print(a)

0.0
[ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]


## Array Index Slicing (just like for lists)

In [9]:
a = np.array(range(10))
b = a[1:-1]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8]


## Mini-breakout Exercise

### Initialize a numpy array of 100 evenly distributed numbers between 0.1 and 2 (inclusive); call it x.
- ### For all the values in x, find $$y = e^x$$

### call the resulting array y.
  


- ### Print the arrays x and y.

In [27]:
x = np.linspace(0.1, 2, 100)
print(x)

y = np.exp(x)
print(y)

[ 0.1         0.11919192  0.13838384  0.15757576  0.17676768  0.1959596
  0.21515152  0.23434343  0.25353535  0.27272727  0.29191919  0.31111111
  0.33030303  0.34949495  0.36868687  0.38787879  0.40707071  0.42626263
  0.44545455  0.46464646  0.48383838  0.5030303   0.52222222  0.54141414
  0.56060606  0.57979798  0.5989899   0.61818182  0.63737374  0.65656566
  0.67575758  0.69494949  0.71414141  0.73333333  0.75252525  0.77171717
  0.79090909  0.81010101  0.82929293  0.84848485  0.86767677  0.88686869
  0.90606061  0.92525253  0.94444444  0.96363636  0.98282828  1.0020202
  1.02121212  1.04040404  1.05959596  1.07878788  1.0979798   1.11717172
  1.13636364  1.15555556  1.17474747  1.19393939  1.21313131  1.23232323
  1.25151515  1.27070707  1.28989899  1.30909091  1.32828283  1.34747475
  1.36666667  1.38585859  1.40505051  1.42424242  1.44343434  1.46262626
  1.48181818  1.5010101   1.52020202  1.53939394  1.55858586  1.57777778
  1.5969697   1.61616162  1.63535354  1.65454545  1.6

## End of wk4-1